package com.pgy.customer.generate;

import java.io.Serializable;

public class Dict implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_dict.id
     *
     * @mbggenerated Mon Jul 17 09:04:36 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_dict.pid
     *
     * @mbggenerated Mon Jul 17 09:04:36 CST 2017
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_dict.p_val
     *
     * @mbggenerated Mon Jul 17 09:04:36 CST 2017
     */
    private String pVal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_dict.dic_code
     *
     * @mbggenerated Mon Jul 17 09:04:36 CST 2017
     */
    private String dicCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_dict.dic_var
     *
     * @mbggenerated Mon Jul 17 09:04:36 CST 2017
     */
    private String dicVar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_dict.dic_val
     *
     * @mbggenerated Mon Jul 17 09:04:36 CST 2017
     */
    private String dicVal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_dict.has_child
     *
     * @mbggenerated Mon Jul 17 09:04:36 CST 2017
     */
    private Boolean hasChild;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_dict.data_type
     *
     * @mbggenerated Mon Jul 17 09:04:36 CST 2017
     */
    private String dataType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_dict.dic_sort
     *
     * @mbggenerated Mon Jul 17 09:04:36 CST 2017
     */
    private Integer dicSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_dict.des
     *
     * @mbggenerated Mon Jul 17 09:04:36 CST 2017
     */
    private String des;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pub_dict
     *
     * @mbggenerated Mon Jul 17 09:04:36 CST 2017
     */
    private static final long serialVersionUID = -3535550585745897072L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_dict.id
     *
     * @return the value of pub_dict.id
     *
     * @mbggenerated Mon Jul 17 09:04:36 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_dict.id
     *
     * @param id the value for pub_dict.id
     *
     * @mbggenerated Mon Jul 17 09:04:36 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_dict.pid
     *
     * @return the value of pub_dict.pid
     *
     * @mbggenerated Mon Jul 17 09:04:36 CST 2017
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_dict.pid
     *
     * @param pid the value for pub_dict.pid
     *
     * @mbggenerated Mon Jul 17 09:04:36 CST 2017
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_dict.p_val
     *
     * @return the value of pub_dict.p_val
     *
     * @mbggenerated Mon Jul 17 09:04:36 CST 2017
     */
    public String getpVal() {
        return pVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_dict.p_val
     *
     * @param pVal the value for pub_dict.p_val
     *
     * @mbggenerated Mon Jul 17 09:04:36 CST 2017
     */
    public void setpVal(String pVal) {
        this.pVal = pVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_dict.dic_code
     *
     * @return the value of pub_dict.dic_code
     *
     * @mbggenerated Mon Jul 17 09:04:36 CST 2017
     */
    public String getDicCode() {
        return dicCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_dict.dic_code
     *
     * @param dicCode the value for pub_dict.dic_code
     *
     * @mbggenerated Mon Jul 17 09:04:36 CST 2017
     */
    public void setDicCode(String dicCode) {
        this.dicCode = dicCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_dict.dic_var
     *
     * @return the value of pub_dict.dic_var
     *
     * @mbggenerated Mon Jul 17 09:04:36 CST 2017
     */
    public String getDicVar() {
        return dicVar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_dict.dic_var
     *
     * @param dicVar the value for pub_dict.dic_var
     *
     * @mbggenerated Mon Jul 17 09:04:36 CST 2017
     */
    public void setDicVar(String dicVar) {
        this.dicVar = dicVar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_dict.dic_val
     *
     * @return the value of pub_dict.dic_val
     *
     * @mbggenerated Mon Jul 17 09:04:36 CST 2017
     */
    public String getDicVal() {
        return dicVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_dict.dic_val
     *
     * @param dicVal the value for pub_dict.dic_val
     *
     * @mbggenerated Mon Jul 17 09:04:36 CST 2017
     */
    public void setDicVal(String dicVal) {
        this.dicVal = dicVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_dict.has_child
     *
     * @return the value of pub_dict.has_child
     *
     * @mbggenerated Mon Jul 17 09:04:36 CST 2017
     */
    public Boolean getHasChild() {
        return hasChild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_dict.has_child
     *
     * @param hasChild the value for pub_dict.has_child
     *
     * @mbggenerated Mon Jul 17 09:04:36 CST 2017
     */
    public void setHasChild(Boolean hasChild) {
        this.hasChild = hasChild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_dict.data_type
     *
     * @return the value of pub_dict.data_type
     *
     * @mbggenerated Mon Jul 17 09:04:36 CST 2017
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_dict.data_type
     *
     * @param dataType the value for pub_dict.data_type
     *
     * @mbggenerated Mon Jul 17 09:04:36 CST 2017
     */
    public void setDataType(String dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_dict.dic_sort
     *
     * @return the value of pub_dict.dic_sort
     *
     * @mbggenerated Mon Jul 17 09:04:36 CST 2017
     */
    public Integer getDicSort() {
        return dicSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_dict.dic_sort
     *
     * @param dicSort the value for pub_dict.dic_sort
     *
     * @mbggenerated Mon Jul 17 09:04:36 CST 2017
     */
    public void setDicSort(Integer dicSort) {
        this.dicSort = dicSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_dict.des
     *
     * @return the value of pub_dict.des
     *
     * @mbggenerated Mon Jul 17 09:04:36 CST 2017
     */
    public String getDes() {
        return des;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_dict.des
     *
     * @param des the value for pub_dict.des
     *
     * @mbggenerated Mon Jul 17 09:04:36 CST 2017
     */
    public void setDes(String des) {
        this.des = des;
    }
}