spring:
  #配置数据源
  datasource:
    url: jdbc:mysql://rm-bp1f6s6m97by4g52u.mysql.rds.aliyuncs.com:3306/pgy_platform_user?useUnicode=true&characterEncoding=utf8
    username: plat
    password: Pugongying2019
